### PR TITLE
Fix sqoop export from TypedPipe

### LINKED ISSUE #400: Sqoop export from TypedPipe generating null output.
The automatically-generated Thrift struct encoders seem to be producing null values.

### PR DESCRIPTION
**Pull request by shmookey**
* Fixes #400, sqoop exports now work with automatically generated encoders.
* Provides a workaround for type bounds on implicit materialisers being ignored by the compiler.
* Updates the sqoop export example to use pipe-based exporting.

### CODE REVIEW

**Comment by stephanh** [comment]
Can you bump the patch version please :+1:

File: maestro-example/src/main/scala/au/com/cba/omnia/maestro/example/CustomerSqoopExportJob.scala [hunk 1]
```diff
@@ -0,0 +1,64 @@
...
+      conf             <- Execution.getConfig.map(CustomerExportConfig(_))
+      uploadInfo       <- upload(conf.upload)
+      sources          <- uploadInfo.withSources
+      (pipe, loadInfo) <- load[Customer](conf.load, uploadInfo.files)
+      loadSuccess      <- loadInfo.withSuccess
+      count            <- sqoopExport(conf.export, pipe)
+    } yield JobFinished
+  }
+
+  def attemptsExceeded = Execution.from(JobNeverReady)   // Elided in the README
```
Comment (rowandavies) [inline maestro-example/src/main/scala/au/com/cba/omnia/maestro/example/CustomerSqoopExportJob.scala]: You can remove the `// Elided in the README` unless we actually add this example to the README.

File: maestro-example/src/test/scala/au/com/cba/omnia/maestro/example/CustomerSqoopExportJobSpec.scala [hunk 2]
```diff
@@ -26,9 +26,11 @@ import au.com.cba.omnia.ebenezer.ParquetLogging
...
 import au.com.cba.omnia.maestro.test.SqoopExecutionTest
 
-object CustomerSqoopExportExecutionSpec extends ThermometerSpec with ParquetLogging { def is = s2"""
+object CustomerSqoopExportJobSpec
+  extends ThermometerSpec
+  with ParquetLogging { def is = s2"""
 
-CustomerSqoopExportExecutionSpec test
+CustomerSqoopExportJobSpec test
 =====================================
```
Comment (rowandavies) [inline maestro-example/src/test/scala/au/com/cba/omnia/maestro/example/CustomerSqoopExportJobSpec.scala]: Good to make the ==== match the length of the test title above.

File: maestro-example/src/main/scala/au/com/cba/omnia/maestro/example/CustomerSqoopExportJob.scala [hunk 3]
```diff
@@ -0,0 +1,64 @@
+//   Copyright 2014 Commonwealth Bank of Australia
```
Comment (rowandavies) [inline maestro-example/src/main/scala/au/com/cba/omnia/maestro/example/CustomerSqoopExportJob.scala]: What's the exact reason for converting from a raw `Execution` to a `Job` extending `MaestroJob`?  This will add a main method, but the tests don't use that.

Comment (rowandavies) [inline maestro-example/src/main/scala/au/com/cba/omnia/maestro/example/CustomerSqoopExportJob.scala]: Happy after discussing this, makes sense to have a Job if it can be considered a whole program.

**Comment by rowandavies** [comment]
:+1:
