### PR TITLE
Better stack trace for `RichExecution.from...` and adds `RichExecution.fromResult`

### LINKED ISSUE #326: Execution.from methods don't have enough information when failing
The Execution.from methods only include the exception of  the future that was supposed to be run but no information about the context in which the future is being run. So you don't actually know where in the code the failure occurred.

### PR DESCRIPTION
**Pull request by stephanh**
Changes the internals of `RichExecution` `fromHive`, `fromHdfs` and `fromEither` to provide a more useful stack trace. The stack trace now shows the location that `fromHdfs` or `fromHive` where called. This closes #326.

Also adds `fromResult`.

### CODE REVIEW

File: maestro-core/src/main/scala/au/com/cba/omnia/maestro/core/scalding/RichExecution.scala [hunk 1]
```diff
@@ -76,24 +81,56 @@ case class RichExecutionObject(exec: Execution.type) {
     * `modifyConf` can be used to update the hive conf that will be used to run the Hive action.
     */
   def fromHive[T](hive: Hive[T], modifyConf: HiveConf => Unit = _ => ()): Execution[T] = {
+    /* Need to get the stack trace outside of the execution so we get a stack trace that is from the
+     * main thread which includes the stack that called this function.
+     */
+    val stacktrace = Thread.currentThread.getStackTrace.tail
```
Comment (SamRoberts) [inline maestro-core/src/main/scala/au/com/cba/omnia/maestro/core/scalding/RichExecution.scala]: Is this expensive?

File: maestro-core/src/main/scala/au/com/cba/omnia/maestro/core/scalding/RichExecution.scala [hunk 2]
```diff
@@ -76,24 +81,56 @@ case class RichExecutionObject(exec: Execution.type) {
     * `modifyConf` can be used to update the hive conf that will be used to run the Hive action.
     */
   def fromHive[T](hive: Hive[T], modifyConf: HiveConf => Unit = _ => ()): Execution[T] = {
+    /* Need to get the stack trace outside of the execution so we get a stack trace that is from the
```
Comment (SamRoberts) [inline maestro-core/src/main/scala/au/com/cba/omnia/maestro/core/scalding/RichExecution.scala]: Did we used to report the stack trace from inside the future's thread? Was there any useful information in there?

Comment (stephanh) [inline maestro-core/src/main/scala/au/com/cba/omnia/maestro/core/scalding/RichExecution.scala]: No. It just provided the stack trace of creating a future within Execution, etc.

File: maestro-core/src/main/scala/au/com/cba/omnia/maestro/core/scalding/RichExecution.scala (hunk 1 above)
Comment (stephanh) [inline maestro-core/src/main/scala/au/com/cba/omnia/maestro/core/scalding/RichExecution.scala]: Getting the stack trace is somewhat expensive according to Google. However, during the lifetime of the project there should only be a couple of calls of these functions.

I'm not really sure of a better way of doing this.

File: maestro-core/src/main/scala/au/com/cba/omnia/maestro/core/scalding/RichExecution.scala [hunk 3]
```diff
@@ -76,24 +81,56 @@ case class RichExecutionObject(exec: Execution.type) {
...
     }
   }
 
+  /**
+    * Helper function to convert a result to a future.
+    *
+    * For errors it creates a top level exception and fills it in with the provided stack trace.
+    * It also prefixes the exception message with the provided prefix.
+    */
+  def resultToFuture[T](
```
Comment (SamRoberts) [inline maestro-core/src/main/scala/au/com/cba/omnia/maestro/core/scalding/RichExecution.scala]: maybe move `resultToFuture` below all the `fromBlah` functions, so all the from functions are grouped together

File: maestro-core/src/main/scala/au/com/cba/omnia/maestro/core/scalding/RichExecution.scala [hunk 4]
```diff
@@ -76,24 +81,56 @@ case class RichExecutionObject(exec: Execution.type) {
...
+    Execution.fromFuture[T](_ => resultToFuture(result, "Operation failed", stacktrace))
+  }
+
   /** Changes from an action that produces a scalaz Disjunction to an Execution. */
   def fromEither[T](disjunction: => String \/ T): Execution[T] =
-    Execution.fromFuture(_ => disjunction.fold(
-      msg => Future.failed(new Exception(msg)),
-      x   => Future.successful(x)
-    ))
+    fromResult(disjunction.fold(Result.fail, Result.ok))
```
Comment (SamRoberts) [inline maestro-core/src/main/scala/au/com/cba/omnia/maestro/core/scalding/RichExecution.scala]: shouldn't you use the string error message as the prefix in the `resultToFuture` call?

File: maestro-core/src/main/scala/au/com/cba/omnia/maestro/core/scalding/RichExecution.scala [hunk 5]
```diff
@@ -76,24 +81,56 @@ case class RichExecutionObject(exec: Execution.type) {
...
+    )
+
+  /** Changes from an action that produces a Result to an Execution. */
+  def fromResult[T](result: => Result[T]): Execution[T] = {
+    /* Need to get the stack trace outside of the execution so we get a stack trace that is from the
+     * main thread which includes the stack that called this function.
+     */
+    val stacktrace = Thread.currentThread.getStackTrace.tail
+
+    Execution.fromFuture[T](_ => resultToFuture(result, "Operation failed", stacktrace))
```
Comment (SamRoberts) [inline maestro-core/src/main/scala/au/com/cba/omnia/maestro/core/scalding/RichExecution.scala]: It's a bit annoying to have a generic "Operation failed" message here, when probably there are perfectly good error messages in the result data structure.

**Comment by SamRoberts** [comment]
I don't know, I like the extra stack trace accuracy, but I'm not sure that it will make day to day debugging any easier to add a generic error layer on top of the actual error message, and it's already hard to get all our users to look at the full exception chain.

File: maestro-core/src/main/scala/au/com/cba/omnia/maestro/core/scalding/RichExecution.scala (hunk 3 above)
Comment (stephanh) [inline maestro-core/src/main/scala/au/com/cba/omnia/maestro/core/scalding/RichExecution.scala]: Will do.

File: maestro-core/src/main/scala/au/com/cba/omnia/maestro/core/scalding/RichExecution.scala (hunk 4 above)
Comment (stephanh) [inline maestro-core/src/main/scala/au/com/cba/omnia/maestro/core/scalding/RichExecution.scala]: No, we pass the error string to `Result.fail` which will create an Error with that error string. `resultToFuture` will extract that error string and make sure it is included in the exception.

File: maestro-core/src/main/scala/au/com/cba/omnia/maestro/core/scalding/RichExecution.scala (hunk 5 above)
Comment (stephanh) [inline maestro-core/src/main/scala/au/com/cba/omnia/maestro/core/scalding/RichExecution.scala]: That is only a prefix for the message or if there is only an exception it is the message of the parent exception.

**Comment by stephanh** [comment]
There are 3 error cases:
* **msg** In which case we return an exception with prefix plus message, so the only thing that has changed is that the exception has a more useful stack trace and the message includes a prefix.
* **msg plus exception** We return an exception with prefix plus message and the original exception as cause. Again the only thing that has changed is the more useful stack trace and the prefix as part of the message.
* **exception** This has changed the most. Previously we would return just the original exception. Now we create a new exception so we can get the better stack trace, set the prefix as message and set the original exception as cause.

When debugging I found it quite annoying that I couldn't see at least where in the Execution flow the error occurred.

**Comment by SamRoberts** [comment]
Sure. Can we just change the **exception** case so that we add the original exception message to the new exception message, similar to the other two cases?

**Comment by stephanh** [comment]
But we keep the original exception. It is the cause for the top level exception. Do you want to duplicate the message and have it at the parent level (with the prefix) and the child level without the prefix?

**Comment by SamRoberts** [comment]
Yeah, exactly. I know it's duplicating the message, but I think it's going to make it a lot easier if the top level exception contains the actual error message.

**Comment by stephanh** [comment]
Ok. I'll do that.

**Comment by SamRoberts** [comment]
Awesome. With that change: :+1:

**Comment by stephanh** [comment]
Done.

File: maestro-core/src/main/scala/au/com/cba/omnia/maestro/core/scalding/RichExecution.scala (hunk 3 above)
Comment (stephanh) [inline maestro-core/src/main/scala/au/com/cba/omnia/maestro/core/scalding/RichExecution.scala]: Done

File: maestro-core/src/main/scala/au/com/cba/omnia/maestro/core/scalding/RichExecution.scala (hunk 1 above)
Comment (vineethvarghese) [inline maestro-core/src/main/scala/au/com/cba/omnia/maestro/core/scalding/RichExecution.scala]: Long time back we used to throw an exception catch it there itself to get the stacktrace out. This sure beats that :).

**Comment by vineethvarghese** [comment]
:+1: Looks good. The issues will still persist if we use just Execution.from. I am curious about how other scalding users cope with this.

**Comment by stephanh** [comment]
We should probably discourage the use of `Execution.from` when an error is expected in favour of using `Execution.fromResult`.

**Comment by rowandavies** [comment]
@stephanh Do you mean `Execution.fromFuture`?
